create extension if not exists postgis;
create type user_role as enum ('vendor','driver','admin');
create type kyc_status as enum ('pending','approved','rejected');
create type order_status as enum ('pending_payment','searching_driver','driver_assigned','picked_up','delivered','cancelled');
create type payment_status as enum ('pending','successful','failed','refunded');

create schema if not exists private;
create table profiles(id uuid primary key references auth.users(id) on delete cascade, role user_role not null, full_name text not null, phone_number text unique not null, email text unique not null, created_at timestamptz default now(), updated_at timestamptz default now());
create table vendors(id uuid primary key default gen_random_uuid(), profile_id uuid unique not null references profiles(id) on delete cascade, business_name text not null, cac_number text, cac_certificate_url text, logo_url text, address text not null, location geography(point,4326) not null, kyc_status kyc_status default 'pending', created_at timestamptz default now());
create table drivers(id uuid primary key default gen_random_uuid(), profile_id uuid unique not null references profiles(id) on delete cascade, company_name text not null, logo_url text, is_active boolean default false, current_location geography(point,4326), wallet_balance numeric(10,2) default 0, kyc_status kyc_status default 'pending', created_at timestamptz default now());
create table orders(id uuid primary key default gen_random_uuid(), vendor_id uuid not null references vendors(id) on delete restrict, driver_id uuid references drivers(id) on delete set null, pickup_address text not null, pickup_location geography(point,4326) not null, delivery_address text not null, delivery_location geography(point,4326) not null, distance_km numeric(6,2) not null check(distance_km>=0), delivery_fee numeric(10,2) not null, platform_commission numeric(10,2) not null, driver_payout numeric(10,2) not null, pickup_otp varchar(4), status order_status default 'pending_payment', created_at timestamptz default now(), updated_at timestamptz default now());
create table payments(id uuid primary key default gen_random_uuid(), order_id uuid unique not null references orders(id) on delete restrict, vendor_id uuid not null references vendors(id) on delete restrict, payment_reference text unique not null, amount numeric(10,2) not null, status payment_status default 'pending', provider text not null default 'paystack', paid_at timestamptz, created_at timestamptz default now());
create table reviews(id uuid primary key default gen_random_uuid(), order_id uuid references orders(id) on delete cascade, reporter_id uuid references profiles(id) on delete cascade, target_id uuid references profiles(id) on delete cascade, rating int check(rating between 1 and 5), complaint_text text, created_at timestamptz default now());

create index vendors_location_gix on vendors using gist(location); create index drivers_location_gix on drivers using gist(current_location); create index orders_pickup_gix on orders using gist(pickup_location); create index orders_vendor_idx on orders(vendor_id); create index orders_driver_idx on orders(driver_id); create index drivers_active_idx on drivers(is_active,kyc_status);

create or replace function public.calculate_delivery_fee(distance_km numeric) returns jsonb language sql immutable as $$ select jsonb_build_object('delivery_fee', case when distance_km<=10 then 1500 else 1500+(ceil(distance_km-10)*150) end,'platform_commission',round((case when distance_km<=10 then 1500 else 1500+(ceil(distance_km-10)*150) end)*.07,2),'driver_payout',round((case when distance_km<=10 then 1500 else 1500+(ceil(distance_km-10)*150) end)*.93,2)); $$;

create or replace function public.nearby_active_drivers(pickup geography, radius_m integer default 5000) returns table(driver_id uuid, profile_id uuid, distance_m double precision) language sql stable as $$ select d.id,d.profile_id,st_distance(d.current_location,pickup) from drivers d where d.is_active=true and d.kyc_status='approved' and d.current_location is not null and st_dwithin(d.current_location,pickup,radius_m) order by d.current_location <-> pickup; $$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,role,full_name,phone_number,email) values(new.id,coalesce((new.raw_app_meta_data->>'role')::user_role,'vendor'),coalesce(new.raw_user_meta_data->>'full_name','New user'),coalesce(new.phone,'pending-'||new.id::text),coalesce(new.email,'')); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function private.generate_pickup_otp() returns text language sql volatile as $$ select lpad((floor(random()*10000))::int::text,4,'0'); $$;
create or replace function public.set_payment_success(p_order uuid,p_reference text) returns void language plpgsql security invoker as $$ declare v_vendor uuid; begin select vendor_id into v_vendor from orders where id=p_order and vendor_id in(select id from vendors where profile_id=auth.uid()); if v_vendor is null then raise exception 'not authorized'; end if; update orders set pickup_otp=private.generate_pickup_otp(),status='searching_driver',updated_at=now() where id=p_order and status='pending_payment'; insert into payments(order_id,vendor_id,payment_reference,amount,status,paid_at) select id,vendor_id,p_reference,delivery_fee,'successful',now() from orders where id=p_order on conflict(order_id) do update set status='successful',payment_reference=excluded.payment_reference,paid_at=now(); end; $$;

create or replace function public.verify_pickup_otp(p_order uuid,p_otp text) returns boolean language plpgsql security invoker as $$ declare ok boolean; begin select exists(select 1 from orders o join drivers d on d.id=o.driver_id where o.id=p_order and d.profile_id=auth.uid() and o.status='driver_assigned' and o.pickup_otp=p_otp and exists(select 1 from payments p where p.order_id=o.id and p.status='successful')) into ok; if ok then update orders set status='picked_up',updated_at=now() where id=p_order; end if; return ok; end; $$;

alter table profiles enable row level security; alter table vendors enable row level security; alter table drivers enable row level security; alter table orders enable row level security; alter table payments enable row level security; alter table reviews enable row level security;
grant select,insert,update on profiles,vendors,drivers,orders,payments,reviews to authenticated; grant execute on function public.calculate_delivery_fee(numeric) to authenticated; grant execute on function public.nearby_active_drivers(geography,integer) to authenticated; grant execute on function public.set_payment_success(uuid,text) to authenticated; grant execute on function public.verify_pickup_otp(uuid,text) to authenticated;
create policy profiles_self on profiles for all to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy vendors_self on vendors for all to authenticated using(profile_id=(select auth.uid())) with check(profile_id=(select auth.uid()));
create policy drivers_self on drivers for all to authenticated using(profile_id=(select auth.uid())) with check(profile_id=(select auth.uid()));
create policy orders_vendor on orders for select to authenticated using(vendor_id in(select id from vendors where profile_id=(select auth.uid())));
create policy orders_driver_assigned on orders for select to authenticated using(driver_id in(select id from drivers where profile_id=(select auth.uid())));
create policy orders_vendor_insert on orders for insert to authenticated with check(vendor_id in(select id from vendors where profile_id=(select auth.uid())));
create policy orders_vendor_update on orders for update to authenticated using(vendor_id in(select id from vendors where profile_id=(select auth.uid()))) with check(vendor_id in(select id from vendors where profile_id=(select auth.uid())));
create policy payments_vendor on payments for select to authenticated using(vendor_id in(select id from vendors where profile_id=(select auth.uid())));
create policy reviews_participant on reviews for all to authenticated using(reporter_id=(select auth.uid()) or target_id=(select auth.uid())) with check(reporter_id=(select auth.uid()));

alter publication supabase_realtime add table orders;
